language: node_js
node_js:
  - "9"
  - "10"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 7
cache:
  directories:
  - node_modules # NPM packages
install: npm install
before_script:
    - npm install -g gulp-cli
    - npm install -g gulp
script:
