language: node_js
node_js:
    - "10"
    - "11"
    - "12"
    - "13"
matrix:
    fast_finish: true
    allow_failures:
        - "10"
cache:
    directories:
    - node_modules # NPM packages
install: npm install
before_script:
    - npm i -g npm
    - npm install -g gulp-cli
    - npm install -g gulp
script:
